import { useGLTF } from "@react-three/drei";
import { ALL_FORM_IDS, FORMS, ROOKIE_IDS } from "../game/creatures";
import { MODEL_HASH } from "./model-manifest";

/**
 * Every form in the roster has a real animated model at /models/<formId>.glb —
 * the roster is deliberately shaped around sourceable models (see CREDITS.md).
 * The procedural creature remains as a Suspense fallback while a model streams in.
 */
/** Shipped models are generated by `npm run optimize-models` from models-src/;
 *  the content hash in the URL busts browser caches whenever a file changes
 *  (models are served with a one-year immutable cache — see public/_headers). */
export const MODEL_PATHS: Partial<Record<string, string>> = Object.fromEntries(
  ALL_FORM_IDS.map((id) => [id, `/models/${id}.glb?v=${MODEL_HASH[id] ?? "0"}`]),
);

/** Target on-board height (world units) every model is normalized to. */
export const TARGET_HEIGHT = 1.25;

/** Per-model orientation/scale fixes for rips that import rotated or odd-sized. */
export interface ModelTweak {
  /** extra rotation [x, y, z] in radians applied to the raw model */
  rot?: [number, number, number];
  /** multiplier on the normalized height */
  scale?: number;
}
export const MODEL_TWEAKS: Record<string, ModelTweak> = {};

export function modelFor(formId: string): string | undefined {
  return MODEL_PATHS[formId];
}

export function tweakFor(formId: string): ModelTweak | undefined {
  return MODEL_TWEAKS[formId];
}

// Rookies load up front (the loading screen waits for them); Champions and Megas
// are fetched in the background right after, so a digivolution or an enemy wave
// almost never has to show the procedural placeholder.
for (const id of ROOKIE_IDS) useGLTF.preload(MODEL_PATHS[id]!);

let restQueued = false;
/** Queue everything else by stage — wild rookies (they open the first waves), then
 *  Champions, then Megas — a few at a time while the browser is idle. */
export function preloadRemainingModels() {
  if (restQueued) return;
  restQueued = true;
  const queue = [1, 2, 3, 4, 5].flatMap((stage) =>
    ALL_FORM_IDS.filter((id) => FORMS[id].stage === stage && !ROOKIE_IDS.includes(id)),
  );
  const idle =
    (window as unknown as { requestIdleCallback?: (cb: () => void) => void }).requestIdleCallback ??
    ((cb: () => void) => setTimeout(cb, 200));
  const next = () => {
    const batch = queue.splice(0, 3);
    for (const id of batch) useGLTF.preload(MODEL_PATHS[id]!);
    if (queue.length) setTimeout(() => idle(next), 350);
  };
  idle(next);
}
