#!/usr/bin/env node
/**
 * Writes src/game/rules-version.ts: a hash of every module in src/game/ — the
 * simulation, the data and the VS rules that each VS client and the lobby worker
 * must agree on. The worker turns away a client whose hash differs from its own, so
 * a tab left open across an update reloads instead of simulating other fights.
 *
 * Runs before `npm run build` and before every worker build (server/wrangler.jsonc),
 * so a deploy always carries the hash of the tree it was built from. Paths resolve
 * from this file, so it can run from any directory.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const dir = fileURLToPath(new URL("../src/game/", import.meta.url));
const OUT = "rules-version.ts";

const hash = createHash("sha256");
for (const file of readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== OUT).sort()) {
  hash.update(file);
  hash.update("\0");
  hash.update(readFileSync(join(dir, file)));
}
const version = hash.digest("hex").slice(0, 12);

const source = `// Generated by scripts/rules-version.mjs — don't edit. A hash of src/game/: the worker
// lets a client into VS only with the rules it runs itself.
export const RULES_VERSION = "${version}";
`;
const out = join(dir, OUT);
if (!existsSync(out) || readFileSync(out, "utf8") !== source) writeFileSync(out, source);
console.log(`rules version ${version}`);
